# Generated by Django 5.0.3 on 2024-03-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('quest_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('reward', models.CharField(max_length=100)),
                ('pc_involved', models.ManyToManyField(to='base.playercharacter')),
            ],
        ),
    ]
