# Generated by Django 5.0.3 on 2024-04-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_quest_description_alter_quest_quest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='pc_involved',
        ),
        migrations.AddField(
            model_name='quest',
            name='pc_involved',
            field=models.TextField(default='[]'),
        ),
    ]
