# Generated by Django 5.0.3 on 2024-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_quest_pc_involved_quest_pc_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTEST',
            fields=[
                ('quest_name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('pc_involved', models.TextField(default='[]')),
                ('is_completed', models.BooleanField(default=False)),
                ('reward', models.CharField(default='check with the DM', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quest',
            name='pc_involved',
        ),
        migrations.AddField(
            model_name='quest',
            name='pc_involved',
            field=models.ManyToManyField(to='base.playercharacter'),
        ),
    ]
